import './styles.css';
import { downloadSessionExport } from './export';
import { buildGraphData, createGraphRenderer, nodeRadius, nodeSummary, nodeTitle } from './graph';
import { createPopupController } from './popup';
import { createSidebarController } from './sidebar';
import type { PopupState, SessionPayload } from './types';

function requireElement<T extends Element>(id: string): T { const element = document.getElementById(id); if (!(element instanceof Element)) throw new Error('Missing required element: #' + id); return element as unknown as T; }
const form = requireElement<HTMLFormElement>('question-form');
const workspace = document.querySelector<HTMLElement>('.workspace'); if (!workspace) throw new Error('Missing required element: .workspace');
const graph = requireElement<HTMLElement>('graph'); const graphPanel = document.querySelector<HTMLElement>('.graph-panel'); if (!graphPanel) throw new Error('Missing required element: .graph-panel');
const graphPopup = requireElement<HTMLElement>('graph-popup'); const graphLive = requireElement<HTMLElement>('graph-live'); const sidebarToggle = requireElement<HTMLButtonElement>('sidebar-toggle');
const status = requireElement<HTMLElement>('status'); const button = requireElement<HTMLButtonElement>('run-button'); const confidenceValue = requireElement<HTMLElement>('confidence-value'); const confidenceMeter = requireElement<HTMLElement>('confidence-meter'); const evidenceList = requireElement<HTMLUListElement>('evidence-list'); const sessionMeta = requireElement<HTMLElement>('session-meta'); const graphMeta = requireElement<HTMLElement>('graph-meta'); const exportMarkdown = requireElement<HTMLButtonElement>('export-markdown'); const exportJson = requireElement<HTMLButtonElement>('export-json'); const exportsSection = requireElement<HTMLElement>('exports'); const replayButton = requireElement<HTMLButtonElement>('replay-button'); const progressList = requireElement<HTMLOListElement>('progress-list');
let activeSessionId = ''; let activeSession: SessionPayload | null = null; let lastGraphSignature: string | null = null; let revealedNodeIds = new Set<string>();
const sidebar = createSidebarController(workspace, sidebarToggle);
const setStatus = (message: string, state = 'running') => { status.textContent = message; status.dataset.state = state; };
const setProgress = (activeIndex: number, complete = false) => { progressList.hidden = false; Array.from(progressList.children).forEach((item, index) => { item.classList.toggle('active', index === activeIndex && !complete); item.classList.toggle('complete', complete || index < activeIndex); }); };
const popupState: PopupState = { selectedNodeId: null };
const popupController = createPopupController({ graph, popup: graphPopup, live: graphLive, state: popupState, title: nodeTitle, summary: nodeSummary, radius: nodeRadius, reducedMotion: () => document.body.classList.contains('reduce-motion') });
const graphRenderer = createGraphRenderer({ graph, popup: graphPopup, onClose: () => popupController.close(), onShow: (node, group) => popupController.show(node, group), onPreview: (node, group) => popupController.showLabel(node, group, true), onRemovePreview: group => popupController.removePreview(group), onNodes: nodes => popupController.setNodes(nodes), onAutoPopup: (node, delay) => { if (!document.body.classList.contains('reduce-motion')) setTimeout(() => popupController.showAutomatic(node), delay); }, reducedMotion: () => document.body.classList.contains('reduce-motion') });
function renderGraph(session: SessionPayload, force = false) { const data = buildGraphData(session); const signature = data.nodes.map(node => node.id).join('|'); if (!force && signature === lastGraphSignature) return; const incoming = new Set(force ? data.nodes.map(node => node.id) : data.nodes.filter(node => !revealedNodeIds.has(node.id)).map(node => node.id)); if (force) revealedNodeIds = new Set(); data.nodes.forEach(node => revealedNodeIds.add(node.id)); lastGraphSignature = signature; graphMeta.textContent = data.rounds + ' debate round' + (data.rounds === 1 ? '' : 's') + ' / ' + session.state.status; graphRenderer.render(data, incoming); }
function renderEvidence(state: SessionPayload['state']) { const evidence = state.evidence?.evidence || []; evidenceList.replaceChildren(); if (!evidence.length) { evidenceList.innerHTML = '<li class="empty">No evidence was returned for this session.</li>'; return; } evidence.forEach(item => { const entry = document.createElement('li'); entry.textContent = item.claim || 'Untitled evidence'; if (item.url) { const link = document.createElement('a'); link.href = item.url; link.target = '_blank'; link.rel = 'noreferrer'; link.textContent = item.source_title || item.url; entry.append(link); } evidenceList.append(entry); }); }
function renderConfidence(state: SessionPayload['state']) { const score = state.confidence?.score; confidenceValue.textContent = Number.isFinite(score) ? String(score) + '%' : '-'; confidenceMeter.style.width = String(Number.isFinite(score) ? score : 0) + '%'; }
async function responseDetail(response: Response, fallback: string) { const body = await response.text(); try { return JSON.parse(body).detail || fallback; } catch { return body || fallback; } }
const delay = (milliseconds: number) => new Promise(resolve => setTimeout(resolve, milliseconds)); const stageProgress: Record<string, number> = { hypothesis: 0, evidence: 1, perspectives: 2, judge: 3, confidence: 3, conclusion: 4 };
async function pollReasoning(sessionId: string): Promise<SessionPayload> { while (true) { await delay(300); const response = await fetch('/api/sessions/' + sessionId); if (!response.ok) throw new Error(await responseDetail(response, 'Unable to read reasoning progress.')); const session = await response.json(); if (session.state.nodes?.length) renderGraph(session); setProgress(stageProgress[session.state.current_stage] ?? 0); if (session.state.status === 'failed') throw new Error(session.state.errors?.at(-1) || 'Reasoning did not complete.'); if (session.state.status === 'completed') return session; } }
const reduceMotion = requireElement<HTMLInputElement>('reduce-motion'); reduceMotion.addEventListener('change', () => document.body.classList.toggle('reduce-motion', reduceMotion.checked));
exportMarkdown.addEventListener('click', () => downloadSessionExport(activeSessionId, 'markdown', setStatus)); exportJson.addEventListener('click', () => downloadSessionExport(activeSessionId, 'json', setStatus)); replayButton.addEventListener('click', () => { if (activeSession) { lastGraphSignature = null; renderGraph(activeSession, true); } }); graphRenderer.renderPendingQuestion();
form.addEventListener('submit', async event => { event.preventDefault(); const question = requireElement<HTMLTextAreaElement>('question').value; sidebar.collapse(); button.disabled = true; graphPanel.setAttribute('aria-busy', 'true'); exportMarkdown.disabled = true; exportJson.disabled = true; exportsSection.hidden = true; replayButton.hidden = true; workspace.classList.remove('session-complete'); lastGraphSignature = null; revealedNodeIds = new Set(); graphRenderer.renderPendingQuestion(question); setProgress(0); setStatus('Building hypothesis...'); try { const createResponse = await fetch('/api/sessions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ question, context: requireElement<HTMLInputElement>('context').value }) }); if (!createResponse.ok) throw new Error(await responseDetail(createResponse, 'Unable to create the session.')); const created = await createResponse.json(); const startResponse = await fetch('/api/sessions/' + created.session_id + '/start', { method: 'POST' }); if (!startResponse.ok) throw new Error(await responseDetail(startResponse, 'Unable to start reasoning.')); activeSession = await pollReasoning(created.session_id); renderGraph(activeSession, true); renderEvidence(activeSession.state); renderConfidence(activeSession.state); activeSessionId = created.session_id; sessionMeta.textContent = 'Session ' + activeSessionId.slice(0, 8) + ' / ' + activeSession.state.iteration + ' reasoning round(s)'; workspace.classList.add('session-complete'); exportsSection.hidden = false; replayButton.hidden = false; exportMarkdown.disabled = false; exportJson.disabled = false; setProgress(4, true); setStatus('Reasoning complete / session ' + activeSessionId.slice(0, 8), 'complete'); } catch (error) { setStatus('Reasoning unavailable: ' + (error instanceof Error ? error.message : String(error)), 'error'); } finally { button.disabled = false; graphPanel.setAttribute('aria-busy', 'false'); } });
