// @ts-nocheck
// Runtime parity bridge: this source is now compiled by Vite as TypeScript.
import './styles.css';

const form = document.getElementById('question-form');
const workspace = document.querySelector('.workspace');
const graph = document.getElementById('graph');
const graphPanel = document.querySelector('.graph-panel');
const graphPopup = document.getElementById('graph-popup');
const graphLive = document.getElementById('graph-live');
const sidebarToggle = document.getElementById('sidebar-toggle');
const status = document.getElementById('status');
const button = document.getElementById('run-button');
const confidenceValue = document.getElementById('confidence-value');
const confidenceMeter = document.getElementById('confidence-meter');
const evidenceList = document.getElementById('evidence-list');
const sessionMeta = document.getElementById('session-meta');
const graphMeta = document.getElementById('graph-meta');
const exportMarkdown = document.getElementById('export-markdown');
const exportJson = document.getElementById('export-json');
const exportsSection = document.getElementById('exports');
const replayButton = document.getElementById('replay-button');
const progressList = document.getElementById('progress-list');
let activeSessionId = null;
let activeSession = null;
let lastGraphSignature = null;
let renderedGraphNodes = [];
let selectedNodeId = null;
let revealedNodeIds = new Set();

const colors = { question: '#5F5E5A', hypothesis: '#BA7517', evidence: '#185FA5', perspective: '#993C1D', conflict: '#A32D2D', judge: '#3B6D11', conclusion: '#534AB7' };
const labels = { question: 'QUESTION', hypothesis: 'HYPOTHESIS', evidence: 'EVIDENCE', perspective: 'PERSPECTIVE', conflict: 'CONFLICT', judge: 'JUDGE', conclusion: 'CONCLUSION', satellite: 'SOURCE' };
const flowOrder = ['hypothesis', 'evidence', 'perspective', 'conflict', 'judge'];
const revealTiming = { mode: 'hybrid', duration: 430, stagger: 42, popupDuration: 900 };

function setStatus(message, state = 'running') { status.textContent = message; status.dataset.state = state; }
function setProgress(activeIndex, complete = false) { progressList.hidden = false; [...progressList.children].forEach((item, index) => { item.classList.toggle('active', index === activeIndex && !complete); item.classList.toggle('complete', complete || index < activeIndex); }); }
function toggleSidebar() { workspace.classList.toggle('sidebar-collapsed'); sidebarToggle.setAttribute('aria-expanded', String(!workspace.classList.contains('sidebar-collapsed'))); }
function renderPendingQuestion(question = '') { const width = graph.clientWidth || 700; const height = graph.clientHeight || 590; graph.innerHTML = `<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Question node waiting for reasoning"><g class="graph-node question" transform="translate(${width / 2},${height / 2})"><circle r="24" stroke="${colors.question}"></circle><text x="0" y="-35" text-anchor="middle">QUESTION</text><text x="0" y="42" text-anchor="middle">${question ? question.slice(0, 38) : 'waiting for input'}</text></g></svg>`; closePopup(); }
function summary(node) { const data = node.data || {}; if (node.satellite) return node.parentType === 'evidence' ? data.claim || data.source_title || data.url || 'Evidence source.' : data.analysis || data.point || data.position || 'Perspective point.'; if (node.type === 'question') return data.question; if (node.type === 'hypothesis') return data.hypotheses?.[0]?.claim || 'Hypothesis generated.'; if (node.type === 'evidence') return data.evidence?.[0]?.claim || 'Evidence evaluated.'; if (node.type === 'perspective') return data.perspectives?.[0]?.analysis || 'Trade-offs analyzed.'; if (node.type === 'conflict') return data.summary || data.conflicts?.[0] || 'Conflict analysis completed.'; if (node.type === 'judge') return data.synthesis || 'Reasoning judged.'; if (node.type === 'conclusion') return data.conclusion || 'Conclusion synthesized.'; return 'Reasoning stage completed.'; }
function nodeTitle(node) { if (node.satellite) return node.parentType === 'evidence' ? 'EVIDENCE SOURCE' : 'PERSPECTIVE POINT'; if (node.type === 'conclusion') return `CONCLUSION / AFTER ROUND ${Math.max(1, node.round - 1)}`; return `${labels[node.type]} / ROUND ${node.round}`; }
function nodeRadius(node) { if (node.satellite) return 6; return node.type === 'question' || node.type === 'conclusion' ? 16 : 10; }
function satelliteItems(node) { if (node.type === 'evidence') return (node.data?.evidence || []).map((item, index) => ({ ...node, id: `${node.id}-source-${index}`, type: 'satellite', satellite: true, parentId: node.id, parentType: 'evidence', data: item })); if (node.type === 'perspective') return (node.data?.perspectives || []).map((item, index) => ({ ...node, id: `${node.id}-point-${index}`, type: 'satellite', satellite: true, parentId: node.id, parentType: 'perspective', data: item })); return []; }
function graphData(session) {
  const stageNodes = (session.state.nodes || []).filter((node) => node.type !== 'confidence').map((node) => ({ ...node, type: node.type === 'perspectives' ? 'perspective' : node.type }));
  const question = { id: 'question-0', type: 'question', round: 0, data: { question: session.question } };
  const primaryNodes = [question, ...stageNodes].sort((a, b) => a.round - b.round || flowOrder.indexOf(a.type) - flowOrder.indexOf(b.type));
  const byRound = new Map(); primaryNodes.forEach((node) => { if (!byRound.has(node.round)) byRound.set(node.round, new Map()); byRound.get(node.round).set(node.type, node); });
  const edges = [];
  [...byRound.keys()].filter((round) => round > 0).sort().forEach((round) => { const current = byRound.get(round); const previous = byRound.get(round - 1); const first = current.get('hypothesis'); if (first) edges.push({ source: round === 1 ? question.id : previous?.get('judge')?.id, target: first.id, kind: round === 1 ? 'flow' : 'continuation' }); flowOrder.slice(1).forEach((type, index) => { const source = current.get(flowOrder[index]); const target = current.get(type); if (source && target) edges.push({ source: source.id, target: target.id, kind: 'flow' }); }); if (previous) flowOrder.forEach((type) => { const source = previous.get(type); const target = current.get(type); if (source && target) edges.push({ source: source.id, target: target.id, kind: 'thread' }); }); });
  const conclusion = primaryNodes.find((node) => node.type === 'conclusion'); const debateRounds = session.state.iteration || 1; const lastJudge = byRound.get(debateRounds)?.get('judge'); if (conclusion && lastJudge) edges.push({ source: lastJudge.id, target: conclusion.id, kind: 'flow' });
  const satellites = primaryNodes.flatMap(satelliteItems); satellites.forEach((node) => edges.push({ source: node.parentId, target: node.id, kind: 'satellite' }));
  return { nodes: [...primaryNodes, ...satellites], edges, rounds: debateRounds };
}

function animateNodes(items, newNodeIds) { const incoming = items.filter(({ node }) => newNodeIds.has(node.id)); items.filter(({ node }) => !newNodeIds.has(node.id)).forEach(({ visual }) => { visual.style.opacity = '1'; visual.style.transform = 'scale(1)'; }); if (document.body.classList.contains('reduce-motion') || !window.anime) { incoming.forEach(({ visual }) => { visual.style.opacity = '1'; visual.style.transform = 'scale(1)'; }); return; } window.anime({ targets: incoming.map(({ visual }) => visual), opacity: [0, 1], scale: [.8, 1], duration: revealTiming.duration, easing: 'easeOutQuad', delay: window.anime.stagger(revealTiming.stagger) }); incoming.forEach((item, index) => scheduleAutoPopup(item, index)); }
function animateEdges(edges) { if (document.body.classList.contains('reduce-motion') || !window.anime) { edges.forEach(finishEdge); return; } window.anime({ targets: edges, strokeDashoffset: (edge) => [Number(edge.dataset.length), 0], opacity: [0.45, 1], duration: 430, easing: 'easeInOutQuad', delay: window.anime.stagger(34), complete: (animation) => animation.animatables.forEach(({ target }) => finishEdge(target)) }); }
function finishEdge(edge) { edge.style.opacity = '1'; edge.setAttribute('stroke-dashoffset', '0'); if (edge.dataset.thread === 'true') edge.setAttribute('stroke-dasharray', '4 4'); }
function labelPlacement(node) { const label = `${nodeTitle(node).replace(' / ', ' · ')}`; const width = Math.max(76, label.length * 6.2 + 16); const height = 18; const outward = Math.hypot(node.x - graph.clientWidth / 2, node.y - graph.clientHeight / 2) || 1; const base = { x: (node.x - graph.clientWidth / 2) / outward, y: (node.y - graph.clientHeight / 2) / outward }; const candidates = [base, { x: -base.x, y: -base.y }, { x: 1, y: 0 }, { x: -1, y: 0 }, { x: 0, y: 1 }, { x: 0, y: -1 }]; return candidates.map((direction) => { const distance = nodeRadius(node) + width / 2 + 10; const x = node.x + direction.x * distance; const y = node.y + direction.y * distance; const left = x - width / 2; const right = x + width / 2; const top = y - height / 2; const bottom = y + height / 2; const clearance = Math.min(...renderedGraphNodes.filter((other) => other.id !== node.id).map((other) => { const nearX = Math.max(left, Math.min(other.x, right)); const nearY = Math.max(top, Math.min(other.y, bottom)); return Math.hypot(other.x - nearX, other.y - nearY) - nodeRadius(other) - 3; }), 999); return { x, y, width, height, clearance }; }).sort((a, b) => b.clearance - a.clearance)[0]; }
function removeNodeLabels() { document.querySelectorAll('.node-label').forEach((label) => label.remove()); }
function showNodeLabel(node, group, preview = false) { removeNodeLabels(); const placement = labelPlacement(node); const wrapper = document.createElementNS('http://www.w3.org/2000/svg', 'g'); wrapper.classList.add('node-label'); if (preview) wrapper.classList.add('preview'); wrapper.setAttribute('transform', `translate(${placement.x - node.x},${placement.y - node.y})`); const visual = document.createElementNS('http://www.w3.org/2000/svg', 'g'); const backplate = document.createElementNS('http://www.w3.org/2000/svg', 'rect'); backplate.setAttribute('x', -placement.width / 2); backplate.setAttribute('y', -placement.height / 2); backplate.setAttribute('width', placement.width); backplate.setAttribute('height', placement.height); backplate.setAttribute('rx', '2'); const text = document.createElementNS('http://www.w3.org/2000/svg', 'text'); text.setAttribute('text-anchor', 'middle'); text.setAttribute('y', '3'); text.textContent = nodeTitle(node).replace(' / ', ' · '); visual.append(backplate, text); wrapper.append(visual); group.append(wrapper); if (preview) requestAnimationFrame(() => { wrapper.style.opacity = '.6'; }); else if (window.anime && !document.body.classList.contains('reduce-motion')) window.anime({ targets: visual, opacity: [0, 1], scale: [.85, 1], duration: 200, easing: 'easeOutQuad' }); }
function popupPosition(node) { const svg = graph.querySelector('svg'); const svgBox = svg.getBoundingClientRect(); const viewBox = svg.viewBox.baseVal; const scaleX = svgBox.width / viewBox.width; const scaleY = svgBox.height / viewBox.height; const anchorX = node.x * scaleX; const anchorY = node.y * scaleY; const popupWidth = 230; const popupHeight = 98; let left = anchorX + 16; let top = anchorY + 16; if (left + popupWidth > graph.clientWidth - 8) left = anchorX - popupWidth - 16; if (top + popupHeight > graph.clientHeight - 8) top = anchorY - popupHeight - 16; return { left: Math.max(8, left), top: Math.max(8, top) }; }
function populatePopup(popup, node) { const position = popupPosition(node); popup.style.left = `${position.left}px`; popup.style.top = `${position.top}px`; popup.innerHTML = `<strong>${nodeTitle(node)}</strong><p>${summary(node)}</p>`; }
function closePopup() { selectedNodeId = null; graphPopup.hidden = true; graphPopup.replaceChildren(); removeNodeLabels(); document.querySelectorAll('.graph-node').forEach((item) => item.classList.remove('selected')); }
function showPopup(node, group, automatic = false) { if (!automatic) { if (selectedNodeId === node.id) { closePopup(); return; } selectedNodeId = node.id; document.querySelectorAll('.graph-node').forEach((item) => item.classList.remove('selected')); removeNodeLabels(); group.classList.add('selected'); showNodeLabel(node, group); populatePopup(graphPopup, node); graphPopup.hidden = false; graphLive.textContent = `${nodeTitle(node)}. ${summary(node)}`; if (window.anime && !document.body.classList.contains('reduce-motion')) window.anime({ targets: graphPopup, opacity: [0, 1], scale: [.85, 1], duration: 200, easing: 'easeOutQuad' }); return; }
  const transient = document.createElement('article'); transient.className = 'graph-popup auto-popup'; transient.setAttribute('aria-hidden', 'true'); graph.append(transient); populatePopup(transient, node); if (window.anime && !document.body.classList.contains('reduce-motion')) { window.anime({ targets: transient, opacity: [0, 1], scale: [.85, 1], duration: 200, easing: 'easeOutQuad', complete: () => setTimeout(() => window.anime({ targets: transient, opacity: [1, 0], duration: 160, easing: 'easeOutQuad', complete: () => transient.remove() }), revealTiming.popupDuration) }); } else setTimeout(() => transient.remove(), revealTiming.popupDuration); }
function scheduleAutoPopup(item, index) { if (revealTiming.mode !== 'hybrid' || document.body.classList.contains('reduce-motion')) return; setTimeout(() => showPopup(item.node, item.group, true), revealTiming.duration + index * revealTiming.stagger); }
function continuationPath(edge, centerX, centerY) { const middleX = (edge.source.x + edge.target.x) / 2; const middleY = (edge.source.y + edge.target.y) / 2; const distance = Math.hypot(middleX - centerX, middleY - centerY) || 1; const reach = Math.max(Math.hypot(edge.source.x - centerX, edge.source.y - centerY), Math.hypot(edge.target.x - centerX, edge.target.y - centerY)) + 42; return `M ${edge.source.x} ${edge.source.y} Q ${centerX + ((middleX - centerX) / distance) * reach} ${centerY + ((middleY - centerY) / distance) * reach} ${edge.target.x} ${edge.target.y}`; }

function renderGraphLayout(data, newNodeIds) {
  selectedNodeId = null; graphPopup.hidden = true; graphPopup.replaceChildren(); graph.replaceChildren(); graph.append(graphPopup); const width = graph.clientWidth || 700; const height = graph.clientHeight || 590; const centerX = width / 2; const centerY = height / 2; const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg'); svg.setAttribute('viewBox', `0 0 ${width} ${height}`); graph.prepend(svg);
  const nodes = data.nodes.map((node) => ({ ...node })); const byId = new Map(nodes.map((node) => [node.id, node])); const links = data.edges.filter((edge) => byId.has(edge.source) && byId.has(edge.target)).map((edge) => ({ ...edge, source: byId.get(edge.source), target: byId.get(edge.target) }));
  if (window.d3?.forceSimulation) { const simulation = window.d3.forceSimulation(nodes).force('link', window.d3.forceLink(links).id((node) => node.id).distance((edge) => edge.kind === 'satellite' ? 28 : edge.kind === 'thread' ? 74 : 92).strength((edge) => edge.kind === 'satellite' ? .95 : edge.kind === 'thread' ? .5 : .62)).force('charge', window.d3.forceManyBody().strength((node) => node.satellite ? -85 : -300)).force('radial', window.d3.forceRadial((node) => node.satellite ? node.round * 108 : node.round * 108, centerX, centerY).strength((node) => node.satellite ? .08 : .3)).force('collide', window.d3.forceCollide((node) => node.satellite ? 10 : node.type === 'question' || node.type === 'conclusion' ? 32 : 26).iterations(2)).stop(); const question = nodes.find((node) => node.type === 'question'); if (question) { question.fx = centerX; question.fy = centerY; } for (let tick = 0; tick < 220; tick += 1) simulation.tick(); } else nodes.forEach((node, index) => { if (node.type === 'question') { node.x = centerX; node.y = centerY; return; } const angle = index * 2.399963229728653; const radius = node.round * 108; node.x = centerX + Math.cos(angle) * radius; node.y = centerY + Math.sin(angle) * radius; });
  renderedGraphNodes = nodes;
  const edgeElements = links.map((edge) => { const path = document.createElementNS('http://www.w3.org/2000/svg', 'path'); path.classList.add('edge', edge.kind); path.setAttribute('d', edge.kind === 'continuation' ? continuationPath(edge, centerX, centerY) : `M ${edge.source.x} ${edge.source.y} L ${edge.target.x} ${edge.target.y}`); path.setAttribute('stroke', edge.kind === 'thread' ? '#8e8b84' : colors[edge.target.parentType || edge.target.type]); svg.append(path); const length = path.getTotalLength(); path.dataset.length = String(length); path.dataset.thread = String(edge.kind === 'thread'); path.setAttribute('stroke-dasharray', `${length} ${length}`); path.setAttribute('stroke-dashoffset', String(length)); path.style.opacity = edge.kind === 'satellite' ? '.35' : '.45'; return path; });
  const nodeItems = nodes.map((node) => { const group = document.createElementNS('http://www.w3.org/2000/svg', 'g'); group.classList.add('graph-node', node.satellite ? 'satellite' : node.type); group.setAttribute('transform', `translate(${node.x},${node.y})`); group.setAttribute('tabindex', '0'); group.setAttribute('role', 'button'); group.setAttribute('aria-label', `${nodeTitle(node)}: ${summary(node)}`); const visual = document.createElementNS('http://www.w3.org/2000/svg', 'g'); visual.classList.add('node-visual'); const circle = document.createElementNS('http://www.w3.org/2000/svg', 'circle'); circle.setAttribute('r', nodeRadius(node)); circle.setAttribute('stroke', colors[node.parentType || node.type]); visual.append(circle); group.append(visual); const activate = () => showPopup(node, group); group.addEventListener('click', (event) => { event.stopPropagation(); activate(); }); group.addEventListener('keydown', (event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); activate(); } }); group.addEventListener('pointerenter', () => { if (window.matchMedia('(pointer: fine)').matches && !group.classList.contains('selected')) showNodeLabel(node, group, true); }); group.addEventListener('pointerleave', () => { const preview = group.querySelector('.node-label.preview'); if (preview) preview.remove(); }); svg.append(group); return { node, group, visual }; });
  svg.addEventListener('click', (event) => { if (!event.target.closest('.graph-node')) closePopup(); }); animateEdges(edgeElements); animateNodes(nodeItems, newNodeIds);
}

function renderGraph(session, force = false) { const data = graphData(session); const signature = data.nodes.map((node) => node.id).join('|'); if (!force && signature === lastGraphSignature) return; const newNodeIds = new Set(force ? data.nodes.map((node) => node.id) : data.nodes.filter((node) => !revealedNodeIds.has(node.id)).map((node) => node.id)); if (force) revealedNodeIds = new Set(); data.nodes.forEach((node) => revealedNodeIds.add(node.id)); lastGraphSignature = signature; // Round 0 is Question; rounds 1..N are debate, while Conclusion is displayed as after round N.
  graphMeta.textContent = `${data.rounds} debate round${data.rounds === 1 ? '' : 's'} / ${session.state.status}`; renderGraphLayout(data, newNodeIds); }
function renderEvidence(state) { const evidence = state.evidence?.evidence || []; evidenceList.replaceChildren(); if (!evidence.length) { evidenceList.innerHTML = '<li class="empty">No evidence was returned for this session.</li>'; return; } evidence.forEach((item) => { const entry = document.createElement('li'); entry.textContent = item.claim || 'Untitled evidence'; if (item.url) { const link = document.createElement('a'); link.href = item.url; link.target = '_blank'; link.rel = 'noreferrer'; link.textContent = item.source_title || item.url; entry.append(link); } evidenceList.append(entry); }); }
function renderConfidence(state) { const score = state.confidence?.score; confidenceValue.textContent = Number.isFinite(score) ? `${score}%` : '-'; confidenceMeter.style.width = `${Number.isFinite(score) ? score : 0}%`; }
async function responseDetail(response, fallback) { const body = await response.text(); try { return JSON.parse(body).detail || fallback; } catch { return body || fallback; } }
document.getElementById('reduce-motion').addEventListener('change', (event) => document.body.classList.toggle('reduce-motion', event.target.checked)); sidebarToggle.addEventListener('click', toggleSidebar);
async function downloadExport(format) { if (!activeSessionId) return; const response = await fetch(`/api/sessions/${activeSessionId}/exports/${format}`); if (!response.ok) { setStatus('Export unavailable for this session.', 'error'); return; } const link = document.createElement('a'); link.href = URL.createObjectURL(await response.blob()); link.download = `thesision-${activeSessionId}.${format === 'markdown' ? 'md' : 'json'}`; link.click(); URL.revokeObjectURL(link.href); }
exportMarkdown.addEventListener('click', () => downloadExport('markdown')); exportJson.addEventListener('click', () => downloadExport('json')); replayButton.addEventListener('click', () => { if (activeSession) { lastGraphSignature = null; renderGraph(activeSession, true); } }); renderPendingQuestion();
const stageProgress = { hypothesis: 0, evidence: 1, perspectives: 2, judge: 3, confidence: 3, conclusion: 4 }; const delay = (milliseconds) => new Promise((resolve) => setTimeout(resolve, milliseconds));
async function pollReasoning(sessionId) { while (true) { await delay(300); const response = await fetch(`/api/sessions/${sessionId}`); if (!response.ok) throw new Error(await responseDetail(response, 'Unable to read reasoning progress.')); const session = await response.json(); const state = session.state; if (state.nodes?.length) renderGraph(session); setProgress(stageProgress[state.current_stage] ?? 0); if (state.status === 'failed') throw new Error(state.errors?.at(-1) || 'Reasoning did not complete.'); if (state.status === 'completed') return session; } }
form.addEventListener('submit', async (event) => { event.preventDefault(); const question = document.getElementById('question').value; workspace.classList.add('sidebar-collapsed'); sidebarToggle.setAttribute('aria-expanded', 'false'); button.disabled = true; graphPanel.setAttribute('aria-busy', 'true'); exportMarkdown.disabled = true; exportJson.disabled = true; exportsSection.hidden = true; replayButton.hidden = true; workspace.classList.remove('session-complete'); lastGraphSignature = null; revealedNodeIds = new Set(); renderPendingQuestion(question); setProgress(0); setStatus('Building hypothesis...'); try { const createResponse = await fetch('/api/sessions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ question, context: document.getElementById('context').value }) }); if (!createResponse.ok) throw new Error(await responseDetail(createResponse, 'Unable to create the session.')); const created = await createResponse.json(); const startResponse = await fetch(`/api/sessions/${created.session_id}/start`, { method: 'POST' }); if (!startResponse.ok) throw new Error(await responseDetail(startResponse, 'Unable to start reasoning.')); activeSession = await pollReasoning(created.session_id); renderGraph(activeSession, true); renderEvidence(activeSession.state); renderConfidence(activeSession.state); activeSessionId = created.session_id; sessionMeta.textContent = `Session ${activeSessionId.slice(0, 8)} / ${activeSession.state.iteration} reasoning round(s)`; workspace.classList.add('session-complete'); exportsSection.hidden = false; replayButton.hidden = false; exportMarkdown.disabled = false; exportJson.disabled = false; setProgress(4, true); setStatus(`Reasoning complete / session ${activeSessionId.slice(0, 8)}`, 'complete'); } catch (error) { setStatus(`Reasoning unavailable: ${error.message}`, 'error'); } finally { button.disabled = false; graphPanel.setAttribute('aria-busy', 'false'); } });
